language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "nightly"
addons:
  apt:
    packages:
      - gfortran
      - libatlas-base-dev
install: pip install -v -r requirements.txt
before_script:
  - pip install requests
script: nosetests
