language: python
cache:
  - apt
  - pip
python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "nightly"
addons:
  apt:
    packages:
      - fort77
      - gfortran
      - libatlas-base-dev
before_script:
  - pip install requests coverage codacy-coverage
script:
  - nosetests --with-coverage --cover-no-print --cover-xml
  - python-codacy-coverage -r coverage.xml
